### ISSUE TITLE
Refactor flow tracker

### ISSUE THREAD

**Issue by talmo** [murthylab/sleap#188]
Implementation needs to more closely match the described algorithm in [Xiao et al. (2018)](https://arxiv.org/abs/1804.06208):
![image](https://user-images.githubusercontent.com/3187454/65639731-b37f0a00-dfb6-11e9-8408-b22b5a6b0285.png)

Namely:
- [x] Greedy assignment instead of Hungarian matching
- [x] Generalize to similarity function and implement OKS/mPCK/etc
- [x] Add bounding box NMS for shifted instances
- [x] Break up into parallelizable sub-modules (e.g., loading, optical flow, matching)
- [ ] Algorithmic correctness tests

Additional enhancements:
- [ ] Allow for max tracks to be set and perform best assignments when possible
